config/routes.rb
Rails.application.routes.draw do
  resources :entities

  resources :reports

end

app/models/entity.rb
class Entity
  include Mongoid::Document 
  include Mongoid::Attributes::Dynamic 
  field :type, type: String
  field :addr, type: String
 # has_and_belongs_to_many :lists
  has_many :reports
end

app/models/report.rb
class Report
	include Mongoid::Document
	include Mongoid::Timestamps::Short # For c_at and u_at.
  	field :status, type: String
  	field :reason, type: String
  	belongs_to :entity 
  	belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps::Created::Short # For c_at and u_at.
  field :provider, type: String
  field :uid, type: String
  field :name, type: String
  field :oauth_token, type: String
  field :oauth_expires_at, type: Time
  has_many :reports
   def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  load 'parser.rb'
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
   if(params[:query])
    q = params[:query]
    s = Parser.parse(q)
    
    s = "Entity"+s.join('')+".all"
    puts s
    @entities = eval(s)

  else
    @entities = Entity.where('name'=>/b/i).all
  
  end
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = Entity.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      params[:entity]
    end
end
#    reg = /[a-zA-Z0-9_\/\s]*:[a-zA-Z0-9_\/\s]*/
#    arr = []
#    q.scan(reg){|m| arr<<m}    
#    query_hash = {}  
#    a = Entity
#    arr.each do |m|
#      m = m.split(':')
#      a = a.where(m[0]=>m[1])
#    end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:status, :reason)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/entities/_form.html.erb
<%= form_for(@entity) do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render 'form' %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

app/views/entities/index.html.erb
<%= form_tag(entities_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :query, params[:query], placeholder: "" %>
  <%= submit_tag "Search", :name => nil %>
<% end %>
Parser that converts input query into mongoid query

Example queries - </br>
name=Bubble sort // when it is an exact match </br>
addr~osconcepts  // equivalent of Entity.where(:addr=>/osconcepts/i)</br>
isleaf=true,type~algorithm //multiple queries can be separated by comma</br>
Count - <%=@entities.count%></br>
<table>
  <thead>
    <tr>
      <td>Type</td>
      <td>addr</td>
    </tr>
  </thead>

  <tbody>
    <% @entities.each do |entity| %>
      <tr>
        <td><%= entity.type %></td>
        <td><%= entity.addr %></td>
        <td><%= link_to 'Show', entity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>
<style>
#query{
  width:300px;
  height: 30px;
  margin-left: 300px;
}
</style>

app/views/entities/new.html.erb
<h1>New entity</h1>

<%= render 'form' %>

<%= link_to 'Back', entities_path %>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>
<% @entity.attributes.each do |k,v|%>
	<b><%=k%></b>  ===  <%=v%>
</br>
<%end%>
<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DqDev</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.status %></td>
        <td><%= report.reason %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @report.status %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @report.reason %>
</p>
<p>
  <strong>Entity contents:</strong>
</br>
<%@report.entity.attributes.each do |k,v|%>
	<strong><%=k%></strong>-<%=v%></br>
<%end%>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>